In [24]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [52]:
import os
import numpy as np
import pandas as pd

In [53]:
import gdown
import optuna
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_absolute_error,mean_squared_error,mean_absolute_percentage_error as mape
from lightgbm import LGBMRegressor

tscv = TimeSeriesSplit(n_splits=3)

In [54]:
import warnings
warnings.filterwarnings('ignore')

In [55]:
datafile_dict={
    "train_transformed_data.csv": "1w_ZOLTTc8WnLj7l8bnwo8Vuz1ii_ZBTY"
    ,"validate_transformed_data.csv" : "1SI5pS8igjgATw5fSPB8hYt5vc62aiVHF"
    ,"test_data.csv" : "1JhzqIAupBjD-vZTqnaAqL1OI9HIpD9O6"
}
#remove existing files
for filename in datafile_dict.keys():
    if os.path.exists(filename):
        os.remove(filename)
        print(f"Removed {filename}")
    else:
        print(f"{filename} not found, skipping removal.")
#doanload new files from drive
for filename, file_id in datafile_dict.items():
  gdown.download(id=file_id, output=filename, quiet=False)

Removed train_transformed_data.csv
Removed validate_transformed_data.csv
Removed test_data.csv

Downloading...
From: https://drive.google.com/uc?id=1w_ZOLTTc8WnLj7l8bnwo8Vuz1ii_ZBTY
To: /content/train_transformed_data.csv
100%|██████████| 28.5M/28.5M [00:00<00:00, 204MB/s]
Downloading...
From: https://drive.google.com/uc?id=1SI5pS8igjgATw5fSPB8hYt5vc62aiVHF
To: /content/validate_transformed_data.csv
100%|██████████| 6.29M/6.29M [00:00<00:00, 229MB/s]
Downloading...
From: https://drive.google.com/uc?id=1JhzqIAupBjD-vZTqnaAqL1OI9HIpD9O6
To: /content/test_data.csv
100%|██████████| 572k/572k [00:00<00:00, 124MB/s]

In [56]:
def load_data_dat(filename):
  if filename.endswith('.csv'):
    df=pd.read_csv(filename)
  return df

train_df= load_data_dat('train_transformed_data.csv')
val_df= load_data_dat('validate_transformed_data.csv')
test_df= load_data_dat('test_data.csv')

In [57]:
FEATURES = [
    'Store_id',#'Store_Type','Location_Type','Region_Code',
    'Store_Type_S1',
       'Store_Type_S2', 'Store_Type_S3', 'Store_Type_S4', 'Location_Type_L1',
       'Location_Type_L2', 'Location_Type_L3', 'Location_Type_L4',
       'Location_Type_L5', 'Region_Code_R1', 'Region_Code_R2',
       'Region_Code_R3', 'Region_Code_R4',
    'Discount_Flag','Holiday',
    'day','month','weekday','weekofyear','is_weekend',
    'lag_1_#Order','lag_7_#Order','rolling_#Order_7',
    'lag_1_Sales','lag_7_Sales','rolling_Sales_7',
    'lag_1_aov',
    'Sales','#Order'
]
FEATURES_ORDERS = [
    'Store_id',#'Store_Type','Location_Type','Region_Code',
    'Store_Type_S1',
       'Store_Type_S2', 'Store_Type_S3', 'Store_Type_S4', 'Location_Type_L1',
       'Location_Type_L2', 'Location_Type_L3', 'Location_Type_L4',
       'Location_Type_L5', 'Region_Code_R1', 'Region_Code_R2',
       'Region_Code_R3', 'Region_Code_R4',
    'Discount_Flag','Holiday',
    'day','month','weekday','weekofyear','is_weekend',
    'lag_1_#Order','lag_7_#Order','rolling_#Order_7',
    'lag_1_Sales','lag_7_Sales','rolling_Sales_7',
    'lag_1_aov'
]

FEATURES_SALES = [
    'Store_id',#'Store_Type','Location_Type','Region_Code',
    'Store_Type_S1',
       'Store_Type_S2', 'Store_Type_S3', 'Store_Type_S4', 'Location_Type_L1',
       'Location_Type_L2', 'Location_Type_L3', 'Location_Type_L4',
       'Location_Type_L5', 'Region_Code_R1', 'Region_Code_R2',
       'Region_Code_R3', 'Region_Code_R4',
    'Discount_Flag','Holiday',
    'day','month','weekday','weekofyear','is_weekend',
    'lag_1_Sales','lag_7_Sales','rolling_Sales_7',
    'lag_1_#Order','lag_7_#Order','rolling_#Order_7',
    'lag_1_aov','pred_orders'
]

column_dtype_map_dict = {'Store_id': 'int64',
 'Store_Type_S1': 'int64',
 'Store_Type_S2': 'int64',
 'Store_Type_S3': 'int64',
 'Store_Type_S4': 'int64',
 'Location_Type_L1': 'int64',
 'Location_Type_L2': 'int64',
 'Location_Type_L3': 'int64',
 'Location_Type_L4': 'int64',
 'Location_Type_L5': 'int64',
 'Region_Code_R1': 'int64',
 'Region_Code_R2': 'int64',
 'Region_Code_R3': 'int64',
 'Region_Code_R4': 'int64',
 'Discount_Flag': 'int64',
 'Holiday': 'int64',
 'day': 'int64',
 'month': 'int64',
 'weekday': 'int64',
 'weekofyear': 'int64',
 'is_weekend': 'int64',
 'lag_1_#Order': 'float64',
 'lag_7_#Order': 'float64',
 'rolling_#Order_7': 'float64',
 'lag_1_Sales': 'float64',
 'lag_7_Sales': 'float64',
 'rolling_Sales_7': 'float64',
 'lag_1_aov': 'float64',
 'Sales': 'float64',
 '#Order': 'float64',
 'pred_orders': 'float64'}

In [58]:
train_df['Date'] = pd.to_datetime(train_df['Date'])
val_df['Date'] = pd.to_datetime(val_df['Date'])
train_df = train_df.sort_values("Date")
val_df = val_df.sort_values("Date")
train_df=train_df[FEATURES]
val_df=val_df[FEATURES]

In [59]:
def format_df_dtype(df, features_dtype_map_dict):
    for col, dtype in features_dtype_map_dict.items():
        if col in df.columns:
            df[col] = df[col].astype(dtype)
    return df

train_df = format_df_dtype(train_df, column_dtype_map_dict)
val_df = format_df_dtype(val_df, column_dtype_map_dict)

#**LightGBM**
---

##**1. Orders**
---

In [60]:
TARGET = "#Order"  # or "#Order"

X = train_df[FEATURES_ORDERS]
y = train_df[TARGET]

In [92]:
def wape(y_true, y_pred):
    return np.sum(np.abs(y_true - y_pred)) / (np.sum(y_true) + 1e-8)

In [62]:
tscv = TimeSeriesSplit(n_splits=3)
mean_metric_scores = []
def objective(trial):

    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 800),
        "num_leaves": trial.suggest_int("num_leaves", 20, 150),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "random_state": 42
    }

    wape_scores = []
    mae_scores = []
    mse_scores = []
    rmse_scores = []
    mape_scores = []

    for train_idx, val_idx in tscv.split(X):

        X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
        y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]

        model = LGBMRegressor(**params)
        model.fit(X_train_fold, y_train_fold)

        preds = model.predict(X_val_fold)
        #score = mean_absolute_error(y_val_fold, preds)
        #score = wape(y_val_fold, preds)

        wape_scores.append(wape(y_val_fold, preds))
        mae_scores.append(mean_absolute_error(y_val_fold, preds))
        mse_scores.append(mean_squared_error(y_val_fold, preds))
        rmse_scores.append(np.sqrt(mean_squared_error(y_val_fold, preds)))
        mape_scores.append(mape(y_val_fold, preds))

    average_metric = np.mean(mae_scores)
    mean_score = mean_metric_scores.append((np.mean(wape_scores),np.mean(mae_scores),np.mean(mse_scores),np.mean(rmse_scores),np.mean(mape_scores),params))
    return average_metric

In [63]:
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=30)

print("Best Params:", study.best_params)
print("Best Score:", study.best_value)

[I 2026-04-20 19:19:13,187] A new study created in memory with name: no-name-974dcb30-30f0-4ef9-b57b-64158aaf167a

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002708 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004852 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008386 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:19:33,457] Trial 0 finished with value: 11.921673866301097 and parameters: {'n_estimators': 530, 'num_leaves': 136, 'learning_rate': 0.29288270670449307, 'subsample': 0.6146023355348684, 'colsample_bytree': 0.8462571673868868}. Best is trial 0 with value: 11.921673866301097.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002395 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005295 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008162 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:19:52,324] Trial 1 finished with value: 12.15433749122016 and parameters: {'n_estimators': 761, 'num_leaves': 53, 'learning_rate': 0.2529494875327431, 'subsample': 0.7447712179622444, 'colsample_bytree': 0.8566231239968625}. Best is trial 0 with value: 11.921673866301097.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002584 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.022388 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.019187 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:20:09,091] Trial 2 finished with value: 11.16430094251834 and parameters: {'n_estimators': 573, 'num_leaves': 32, 'learning_rate': 0.05701765481741746, 'subsample': 0.8318153687756801, 'colsample_bytree': 0.6499557397789614}. Best is trial 2 with value: 11.16430094251834.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002759 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005181 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007385 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:20:24,306] Trial 3 finished with value: 12.066519104030762 and parameters: {'n_estimators': 636, 'num_leaves': 50, 'learning_rate': 0.28245934367541775, 'subsample': 0.8274453269735736, 'colsample_bytree': 0.7914304147930338}. Best is trial 2 with value: 11.16430094251834.

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005572 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004344 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007501 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:20:45,312] Trial 4 finished with value: 11.540432451619523 and parameters: {'n_estimators': 685, 'num_leaves': 87, 'learning_rate': 0.22631506925947448, 'subsample': 0.771780196178551, 'colsample_bytree': 0.720964046021772}. Best is trial 2 with value: 11.16430094251834.

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010488 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005439 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.029698 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:21:05,831] Trial 5 finished with value: 11.04007301761027 and parameters: {'n_estimators': 495, 'num_leaves': 92, 'learning_rate': 0.053849036888741444, 'subsample': 0.6631265620667472, 'colsample_bytree': 0.7393553501447793}. Best is trial 5 with value: 11.04007301761027.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002995 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.022500 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008579 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:21:19,787] Trial 6 finished with value: 11.174408394920833 and parameters: {'n_estimators': 264, 'num_leaves': 134, 'learning_rate': 0.07433260369242536, 'subsample': 0.6940393600375698, 'colsample_bytree': 0.9115310448624675}. Best is trial 5 with value: 11.04007301761027.

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005938 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005087 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006742 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:21:35,975] Trial 7 finished with value: 11.588567592557851 and parameters: {'n_estimators': 523, 'num_leaves': 96, 'learning_rate': 0.21066371793690813, 'subsample': 0.9995261986837674, 'colsample_bytree': 0.6267380567531481}. Best is trial 5 with value: 11.04007301761027.

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011920 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005066 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007656 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:21:57,832] Trial 8 finished with value: 11.234896767543065 and parameters: {'n_estimators': 589, 'num_leaves': 111, 'learning_rate': 0.1250528894635882, 'subsample': 0.921380849040892, 'colsample_bytree': 0.9627662709990645}. Best is trial 5 with value: 11.04007301761027.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002332 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.019510 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007149 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:22:09,684] Trial 9 finished with value: 12.055928224984491 and parameters: {'n_estimators': 428, 'num_leaves': 80, 'learning_rate': 0.23830845764561123, 'subsample': 0.9739175196322565, 'colsample_bytree': 0.6677762923396035}. Best is trial 5 with value: 11.04007301761027.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002434 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005229 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007519 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:22:29,092] Trial 10 finished with value: 10.569765508474879 and parameters: {'n_estimators': 362, 'num_leaves': 117, 'learning_rate': 0.01953059420950925, 'subsample': 0.6024129987517324, 'colsample_bytree': 0.7518896308328902}. Best is trial 10 with value: 10.569765508474879.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002587 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004961 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007348 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:22:48,437] Trial 11 finished with value: 10.581809370567585 and parameters: {'n_estimators': 380, 'num_leaves': 112, 'learning_rate': 0.015509555153555994, 'subsample': 0.614767161449682, 'colsample_bytree': 0.7521165045734493}. Best is trial 10 with value: 10.569765508474879.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002358 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011441 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007696 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:23:07,740] Trial 12 finished with value: 10.382896474085692 and parameters: {'n_estimators': 343, 'num_leaves': 114, 'learning_rate': 0.01108019477729205, 'subsample': 0.6017693529578273, 'colsample_bytree': 0.7481295732862226}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002441 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004847 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.029505 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:23:20,510] Trial 13 finished with value: 10.633395894956942 and parameters: {'n_estimators': 206, 'num_leaves': 150, 'learning_rate': 0.01045182075557911, 'subsample': 0.6955958112662619, 'colsample_bytree': 0.7002395992547258}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002465 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004855 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.029545 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:23:33,100] Trial 14 finished with value: 11.144208423017242 and parameters: {'n_estimators': 338, 'num_leaves': 116, 'learning_rate': 0.14739287741670257, 'subsample': 0.6044122880299005, 'colsample_bytree': 0.8036588793198306}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002817 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004918 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007715 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:23:43,549] Trial 15 finished with value: 11.341578162462595 and parameters: {'n_estimators': 313, 'num_leaves': 71, 'learning_rate': 0.09065855962899735, 'subsample': 0.6655602310032479, 'colsample_bytree': 0.7910245945285941}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002394 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004612 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.026714 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:23:58,689] Trial 16 finished with value: 11.394798634453432 and parameters: {'n_estimators': 443, 'num_leaves': 129, 'learning_rate': 0.18819147862151603, 'subsample': 0.8879784232438566, 'colsample_bytree': 0.6080592536014789}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002501 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004633 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.027013 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:24:08,729] Trial 17 finished with value: 11.15668068367107 and parameters: {'n_estimators': 263, 'num_leaves': 105, 'learning_rate': 0.1025491213823329, 'subsample': 0.734429877856526, 'colsample_bytree': 0.6845849659320596}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002563 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004854 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008177 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:24:29,384] Trial 18 finished with value: 10.973149218915509 and parameters: {'n_estimators': 407, 'num_leaves': 150, 'learning_rate': 0.03925328975671925, 'subsample': 0.6638900717453353, 'colsample_bytree': 0.8631740366824183}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004359 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005175 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007361 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:24:46,123] Trial 19 finished with value: 10.864469045696358 and parameters: {'n_estimators': 330, 'num_leaves': 125, 'learning_rate': 0.03807971045197229, 'subsample': 0.6382351768779329, 'colsample_bytree': 0.7563773586986761}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002682 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005438 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007268 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:24:52,400] Trial 20 finished with value: 11.740393194630457 and parameters: {'n_estimators': 206, 'num_leaves': 74, 'learning_rate': 0.18078852315531277, 'subsample': 0.722244144137502, 'colsample_bytree': 0.9013303118185454}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002358 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005097 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008397 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:25:12,383] Trial 21 finished with value: 10.565465016236509 and parameters: {'n_estimators': 383, 'num_leaves': 105, 'learning_rate': 0.01543372727464578, 'subsample': 0.6041018721609807, 'colsample_bytree': 0.7657363253430329}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002727 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005088 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007426 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:25:30,452] Trial 22 finished with value: 10.612137461135399 and parameters: {'n_estimators': 370, 'num_leaves': 102, 'learning_rate': 0.01751692452480194, 'subsample': 0.6390724505014237, 'colsample_bytree': 0.772430959282125}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002406 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004426 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007898 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:25:48,800] Trial 23 finished with value: 11.059513319021795 and parameters: {'n_estimators': 443, 'num_leaves': 121, 'learning_rate': 0.07454439547482733, 'subsample': 0.6005300898944319, 'colsample_bytree': 0.7179398273380806}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002566 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004785 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007569 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:26:01,524] Trial 24 finished with value: 10.756644262044889 and parameters: {'n_estimators': 265, 'num_leaves': 100, 'learning_rate': 0.03415264679520694, 'subsample': 0.6926156120893983, 'colsample_bytree': 0.8250243577763335}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002344 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004981 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007183 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:26:19,179] Trial 25 finished with value: 11.408625245340344 and parameters: {'n_estimators': 460, 'num_leaves': 135, 'learning_rate': 0.12347954451989561, 'subsample': 0.64395278911423, 'colsample_bytree': 0.7306148740550551}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002384 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008228 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007512 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:26:29,663] Trial 26 finished with value: 11.266919649649637 and parameters: {'n_estimators': 295, 'num_leaves': 63, 'learning_rate': 0.06752545161277378, 'subsample': 0.7795216053424813, 'colsample_bytree': 0.81956049542463}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002592 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005143 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008602 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:26:46,469] Trial 27 finished with value: 10.959942695532911 and parameters: {'n_estimators': 372, 'num_leaves': 108, 'learning_rate': 0.034686260160495766, 'subsample': 0.6322417851208995, 'colsample_bytree': 0.7745917779099021}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002426 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004493 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007750 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:27:02,593] Trial 28 finished with value: 10.98494886033866 and parameters: {'n_estimators': 401, 'num_leaves': 118, 'learning_rate': 0.09011805267436163, 'subsample': 0.6788271999278775, 'colsample_bytree': 0.6970637527685515}. Best is trial 12 with value: 10.382896474085692.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002560 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2050
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 28
[LightGBM] [Info] Start training from score 67.524810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005000 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2132
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 28
[LightGBM] [Info] Start training from score 68.211554
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007738 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2156
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 28
[LightGBM] [Info] Start training from score 67.961727

[I 2026-04-20 19:27:31,927] Trial 29 finished with value: 10.582227224109019 and parameters: {'n_estimators': 475, 'num_leaves': 140, 'learning_rate': 0.010515532425466718, 'subsample': 0.6226078234167051, 'colsample_bytree': 0.89295634647334}. Best is trial 12 with value: 10.382896474085692.

Best Params: {'n_estimators': 343, 'num_leaves': 114, 'learning_rate': 0.01108019477729205, 'subsample': 0.6017693529578273, 'colsample_bytree': 0.7481295732862226}
Best Score: 10.382896474085692

In [64]:
formatted_data = []
for wape, mae, mse, rmse, mape, params in mean_metric_scores:
    # Combine metrics and the params dictionary into one flat dict
    row = {
        'WAPE': wape, 'MAE': mae, 'MSE': mse, 
        'RMSE': rmse, 'MAPE': mape
    }
    row.update(params)
    formatted_data.append(row)

df = pd.DataFrame(formatted_data)
df

,WAPE,MAE,MSE,RMSE,MAPE,n_estimators,num_leaves,learning_rate,subsample,colsample_bytree,random_state
0,0.175411,11.921674,274.944617,16.524898,3.997833e+13,530,136,0.292883,0.614602,0.846257,42
1,0.178813,12.154337,286.191204,16.857190,4.095294e+13,761,53,0.252949,0.744771,0.856623,42
2,0.164265,11.164301,246.809541,15.626903,4.402408e+13,573,32,0.057018,0.831815,0.649956,42
3,0.177619,12.066519,282.487720,16.778893,4.458311e+13,636,50,0.282459,0.827445,0.791430,42
4,0.169846,11.540432,265.779625,16.245712,4.234197e+13,685,87,0.226315,0.771780,0.720964,42
5,0.162425,11.040073,240.140744,15.424158,4.161602e+13,495,92,0.053849,0.663127,0.739355,42
6,0.164430,11.174408,249.171826,15.723206,4.312601e+13,264,134,0.074333,0.694039,0.911531,42
7,0.170529,11.588568,264.660116,16.222575,4.296025e+13,523,96,0.210664,0.999526,0.626738,42
8,0.165313,11.234897,250.336312,15.762134,4.294972e+13,589,111,0.125053,0.921381,0.962766,42
9,0.177378,12.055928,277.647556,16.597750,4.333154e+13,428,80,0.238308,0.973918,0.667776,42
10,0.155543,10.569766,225.263216,14.937554,4.378024e+13,362,117,0.019531,0.602413,0.751890,42
11,0.155719,10.581809,225.520967,14.950820,4.510800e+13,380,112,0.015510,0.614767,0.752117,42
12,0.152813,10.382896,218.583265,14.712105,4.504972e+13,343,114,0.011080,0.601769,0.748130,42
13,0.156530,10.633396,226.989242,14.989615,4.259044e+13,206,150,0.010452,0.695596,0.700240,42
14,0.163986,11.144208,249.499979,15.740583,4.102234e+13,338,116,0.147393,0.604412,0.803659,42
15,0.166870,11.341578,251.696665,15.794922,4.328376e+13,313,71,0.090659,0.665560,0.791025,42
16,0.167673,11.394799,256.563396,15.953437,4.080455e+13,443,129,0.188191,0.887978,0.608059,42
17,0.164129,11.156681,246.572344,15.624532,4.329389e+13,263,105,0.102549,0.734430,0.684585,42
18,0.161441,10.973149,239.873234,15.413698,4.257779e+13,407,150,0.039253,0.663890,0.863174,42
19,0.159871,10.864469,235.017288,15.261135,4.366315e+13,330,125,0.038080,0.638235,0.756377,42
20,0.172765,11.740393,270.289853,16.395715,4.386679e+13,206,74,0.180789,0.722244,0.901330,42
21,0.155478,10.565465,224.860524,14.925358,4.456334e+13,383,105,0.015434,0.604102,0.765736,42
22,0.156169,10.612137,227.209935,15.006082,4.490309e+13,370,102,0.017517,0.639072,0.772431,42
23,0.162719,11.059513,240.491334,15.437430,4.186080e+13,443,121,0.074544,0.600530,0.717940,42
24,0.158280,10.756644,231.932040,15.157336,4.447451e+13,265,100,0.034153,0.692616,0.825024,42
25,0.167889,11.408625,255.216244,15.935178,4.211080e+13,460,135,0.123480,0.643953,0.730615,42
26,0.165763,11.266920,249.629317,15.722385,4.412979e+13,295,63,0.067525,0.779522,0.819560,42
27,0.161248,10.959943,238.668127,15.364784,4.335196e+13,372,108,0.034686,0.632242,0.774592,42
28,0.161674,10.984949,241.792102,15.499566,4.202890e+13,401,118,0.090118,0.678827,0.697064,42
29,0.155736,10.582227,227.500922,15.009392,4.495273e+13,475,140,0.010516,0.622608,0.892956,42

In [65]:
df.to_csv('lightgbm_errorfile_orders.csv', header=True, index=False)

In [66]:
study.best_params

{'n_estimators': 343,
 'num_leaves': 114,
 'learning_rate': 0.01108019477729205,
 'subsample': 0.6017693529578273,
 'colsample_bytree': 0.7481295732862226}

##**2. Sales**
---

In [93]:
train_df= load_data_dat('train_transformed_data.csv')
val_df= load_data_dat('validate_transformed_data.csv')
test_df= load_data_dat('test_data.csv')

In [94]:
train_df['Date'] = pd.to_datetime(train_df['Date'])
val_df['Date'] = pd.to_datetime(val_df['Date'])
train_df = train_df.sort_values("Date")
val_df = val_df.sort_values("Date")
train_df=train_df[FEATURES]
val_df=val_df[FEATURES]

In [95]:
def format_df_dtype(df, features_dtype_map_dict):
    for col, dtype in features_dtype_map_dict.items():
        if col in df.columns:
            df[col] = df[col].astype(dtype)
    return df

train_df = format_df_dtype(train_df, column_dtype_map_dict)
val_df = format_df_dtype(val_df, column_dtype_map_dict)

In [96]:
TARGET = "#Order"  # or "#Order"

X = train_df[FEATURES_ORDERS]
y = train_df[TARGET]

In [97]:
order_params = {
            'n_estimators': 343,
            'num_leaves': 114,
            'learning_rate': 0.01108019477729205,
            'subsample': 0.6017693529578273,
            'colsample_bytree': 0.7481295732862226
            }
model_orders = LGBMRegressor(**order_params)

model_orders.fit(X, y)
X['pred_orders'] = model_orders.predict(X)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009272 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2177
[LightGBM] [Info] Number of data points in the train set: 144540, number of used features: 28
[LightGBM] [Info] Start training from score 67.815373

In [98]:
X[X['Store_id'] == 1].head(10)

,Store_id,Store_Type_S1,Store_Type_S2,Store_Type_S3,Store_Type_S4,Location_Type_L1,Location_Type_L2,Location_Type_L3,Location_Type_L4,Location_Type_L5,...,weekofyear,is_weekend,lag_1_#Order,lag_7_#Order,rolling_#Order_7,lag_1_Sales,lag_7_Sales,rolling_Sales_7,lag_1_aov,pred_orders
0,1,1,0,0,0,0,0,1,0,0,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.459403
1,1,1,0,0,0,0,0,1,0,0,...,1,0,9.0,NaN,NaN,7011.84,NaN,NaN,701.184000,56.238974
2,1,1,0,0,0,0,0,1,0,0,...,1,0,60.0,NaN,NaN,42369.00,NaN,NaN,694.573770,60.774135
3,1,1,0,0,0,0,0,1,0,0,...,1,0,72.0,NaN,NaN,50037.00,NaN,NaN,685.438356,68.634013
4,1,1,0,0,0,0,0,1,0,0,...,1,0,64.0,NaN,NaN,44397.00,NaN,NaN,683.030769,65.637383
5,1,1,0,0,0,0,0,1,0,0,...,1,1,63.0,NaN,NaN,47604.00,NaN,NaN,743.812500,50.714325
6,1,1,0,0,0,0,0,1,0,0,...,1,1,36.0,NaN,NaN,24495.00,NaN,NaN,662.027027,54.544784
7,1,1,0,0,0,0,0,1,0,0,...,2,0,55.0,9.0,51.285714,36855.00,7011.84,36109.834286,658.125000,47.728801
8,1,1,0,0,0,0,0,1,0,0,...,2,0,52.0,60.0,57.428571,34101.00,42369.00,39979.714286,643.415094,50.145698
9,1,1,0,0,0,0,0,1,0,0,...,2,0,65.0,72.0,58.142857,42429.00,50037.00,39988.285714,642.863636,48.580716

In [99]:
TARGET = 'Sales'
y = train_df[TARGET]

In [100]:
tscv = TimeSeriesSplit(n_splits=3)
mean_metric_scores = []
def objective(trial):

    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 800),
        "num_leaves": trial.suggest_int("num_leaves", 20, 150),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "random_state": 42
    }

    wape_scores = []
    mae_scores = []
    mse_scores = []
    rmse_scores = []
    mape_scores = []

    for train_idx, val_idx in tscv.split(X):

        X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
        y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]

        model = LGBMRegressor(**params)
        model.fit(X_train_fold, y_train_fold)

        preds = model.predict(X_val_fold)
        #score = mean_absolute_error(y_val_fold, preds)
        #score = wape(y_val_fold, preds)

        wape_scores.append(wape(y_val_fold, preds))
        mae_scores.append(mean_absolute_error(y_val_fold, preds))
        mse_scores.append(mean_squared_error(y_val_fold, preds))
        rmse_scores.append(np.sqrt(mean_squared_error(y_val_fold, preds)))
        #mape_scores.append(mape(y_val_fold, preds))

    average_metric = np.mean(mae_scores)
    mean_score = mean_metric_scores.append((
                                np.mean(wape_scores), 
                                np.mean(mae_scores), 
                                np.mean(mse_scores), 
                                np.mean(rmse_scores), 
                                0,  # Placeholder for MAPE since it's commented out
                                params
                            ))
    return average_metric

In [101]:
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=30)

print("Best Params:", study.best_params)
print("Best Score:", study.best_value)

[I 2026-04-20 19:35:41,411] A new study created in memory with name: no-name-9e2dfb83-c9c9-4540-8b25-9869ab095bc2

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002227 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020498 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.016787 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:36:00,663] Trial 0 finished with value: 5911.578657104874 and parameters: {'n_estimators': 663, 'num_leaves': 42, 'learning_rate': 0.04957091395476058, 'subsample': 0.6121078554295055, 'colsample_bytree': 0.612862273403987}. Best is trial 0 with value: 5911.578657104874.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002684 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005677 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.013925 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:36:17,892] Trial 1 finished with value: 5767.128768377807 and parameters: {'n_estimators': 405, 'num_leaves': 126, 'learning_rate': 0.07972829044809913, 'subsample': 0.6148952515731863, 'colsample_bytree': 0.8751099410795926}. Best is trial 1 with value: 5767.128768377807.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003043 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005090 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020279 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:36:43,544] Trial 2 finished with value: 6292.973878611803 and parameters: {'n_estimators': 646, 'num_leaves': 134, 'learning_rate': 0.17576850149833165, 'subsample': 0.8098663145497543, 'colsample_bytree': 0.661866368680877}. Best is trial 1 with value: 5767.128768377807.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002556 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012176 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008119 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:36:57,873] Trial 3 finished with value: 6052.546913853718 and parameters: {'n_estimators': 444, 'num_leaves': 76, 'learning_rate': 0.13348028483314875, 'subsample': 0.9851231536428108, 'colsample_bytree': 0.9288098947593462}. Best is trial 1 with value: 5767.128768377807.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002825 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005010 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007589 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:37:18,574] Trial 4 finished with value: 6585.433538667873 and parameters: {'n_estimators': 640, 'num_leaves': 94, 'learning_rate': 0.2523338814237422, 'subsample': 0.7594574802243463, 'colsample_bytree': 0.8999305139450509}. Best is trial 1 with value: 5767.128768377807.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002377 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004592 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.017561 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:37:36,274] Trial 5 finished with value: 6239.074918941824 and parameters: {'n_estimators': 643, 'num_leaves': 65, 'learning_rate': 0.17888749520341465, 'subsample': 0.6043391262234202, 'colsample_bytree': 0.6741262444026931}. Best is trial 1 with value: 5767.128768377807.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003003 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005176 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.034926 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:38:01,852] Trial 6 finished with value: 5742.279253005713 and parameters: {'n_estimators': 494, 'num_leaves': 117, 'learning_rate': 0.029544072759293397, 'subsample': 0.8494015759839609, 'colsample_bytree': 0.8625930945523053}. Best is trial 6 with value: 5742.279253005713.

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009937 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005426 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007367 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:38:14,122] Trial 7 finished with value: 6173.889405551284 and parameters: {'n_estimators': 318, 'num_leaves': 135, 'learning_rate': 0.28616440412651484, 'subsample': 0.9309658600647028, 'colsample_bytree': 0.8550483520285634}. Best is trial 6 with value: 5742.279253005713.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002633 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012007 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.027899 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:38:37,226] Trial 8 finished with value: 6031.296556699777 and parameters: {'n_estimators': 765, 'num_leaves': 49, 'learning_rate': 0.07018975347969307, 'subsample': 0.8754712007980495, 'colsample_bytree': 0.7498820561214388}. Best is trial 6 with value: 5742.279253005713.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002563 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.018762 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007383 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:38:50,390] Trial 9 finished with value: 6097.1606636947 and parameters: {'n_estimators': 386, 'num_leaves': 110, 'learning_rate': 0.18434008788219575, 'subsample': 0.8651287022514818, 'colsample_bytree': 0.760802903569702}. Best is trial 6 with value: 5742.279253005713.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002572 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006211 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007768 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:39:16,338] Trial 10 finished with value: 5722.638807293394 and parameters: {'n_estimators': 526, 'num_leaves': 101, 'learning_rate': 0.022902475346007492, 'subsample': 0.7313755710410165, 'colsample_bytree': 0.9804552586783788}. Best is trial 10 with value: 5722.638807293394.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004293 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005485 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008263 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:39:47,402] Trial 11 finished with value: 5649.111947789842 and parameters: {'n_estimators': 534, 'num_leaves': 100, 'learning_rate': 0.011728045747338545, 'subsample': 0.7308946221452833, 'colsample_bytree': 0.9982200377916092}. Best is trial 11 with value: 5649.111947789842.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002785 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009002 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008029 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:40:18,012] Trial 12 finished with value: 5637.733865263351 and parameters: {'n_estimators': 547, 'num_leaves': 96, 'learning_rate': 0.010592283621485154, 'subsample': 0.7135763817541183, 'colsample_bytree': 0.9865028594802613}. Best is trial 12 with value: 5637.733865263351.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002765 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008244 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008460 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:40:27,147] Trial 13 finished with value: 5888.2009372244065 and parameters: {'n_estimators': 237, 'num_leaves': 82, 'learning_rate': 0.1111663471033599, 'subsample': 0.6949725372166191, 'colsample_bytree': 0.9912011410057252}. Best is trial 12 with value: 5637.733865263351.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002572 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005391 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008803 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:40:39,868] Trial 14 finished with value: 5926.084412372661 and parameters: {'n_estimators': 550, 'num_leaves': 24, 'learning_rate': 0.08787046210902393, 'subsample': 0.6886853977056709, 'colsample_bytree': 0.9580533587478436}. Best is trial 12 with value: 5637.733865263351.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002629 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004893 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007376 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002741 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008660 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008295 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:41:39,742] Trial 16 finished with value: 6602.903824469863 and parameters: {'n_estimators': 746, 'num_leaves': 95, 'learning_rate': 0.2136763197405935, 'subsample': 0.7732833644907452, 'colsample_bytree': 0.9338308585728791}. Best is trial 12 with value: 5637.733865263351.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002740 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005219 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.014169 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:41:53,245] Trial 17 finished with value: 6152.239920310618 and parameters: {'n_estimators': 467, 'num_leaves': 62, 'learning_rate': 0.11658461451029223, 'subsample': 0.7337188252101513, 'colsample_bytree': 0.9988982422341882}. Best is trial 12 with value: 5637.733865263351.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002731 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005192 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008126 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:42:10,829] Trial 18 finished with value: 5573.198909679556 and parameters: {'n_estimators': 320, 'num_leaves': 105, 'learning_rate': 0.010724139467205324, 'subsample': 0.8058701803357772, 'colsample_bytree': 0.9257073909201444}. Best is trial 18 with value: 5573.198909679556.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002824 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005245 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008054 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:42:20,184] Trial 19 finished with value: 5706.306102401788 and parameters: {'n_estimators': 210, 'num_leaves': 76, 'learning_rate': 0.05323692475298256, 'subsample': 0.812691754554536, 'colsample_bytree': 0.9138424268465667}. Best is trial 18 with value: 5573.198909679556.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002716 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.018748 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008087 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:42:35,136] Trial 20 finished with value: 5818.316611160146 and parameters: {'n_estimators': 329, 'num_leaves': 117, 'learning_rate': 0.05450283447143564, 'subsample': 0.6557963002733259, 'colsample_bytree': 0.8021440819028871}. Best is trial 18 with value: 5573.198909679556.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002943 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005485 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008250 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:43:04,854] Trial 21 finished with value: 5746.681359327566 and parameters: {'n_estimators': 592, 'num_leaves': 98, 'learning_rate': 0.023828149371070022, 'subsample': 0.7355199162699371, 'colsample_bytree': 0.9517670085459841}. Best is trial 18 with value: 5573.198909679556.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003694 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005657 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.035120 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:43:22,667] Trial 22 finished with value: 5564.337688439678 and parameters: {'n_estimators': 294, 'num_leaves': 113, 'learning_rate': 0.014560582047605566, 'subsample': 0.8220865020527265, 'colsample_bytree': 0.9632820171720197}. Best is trial 22 with value: 5564.337688439678.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002503 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.019893 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007548 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:43:36,417] Trial 23 finished with value: 5741.164750139013 and parameters: {'n_estimators': 286, 'num_leaves': 109, 'learning_rate': 0.05058377978672951, 'subsample': 0.9069458607801613, 'colsample_bytree': 0.8954458564756022}. Best is trial 22 with value: 5564.337688439678.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002812 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008626 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007946 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:43:49,658] Trial 24 finished with value: 5899.5468241182125 and parameters: {'n_estimators': 379, 'num_leaves': 86, 'learning_rate': 0.09512600988270879, 'subsample': 0.8369870634690506, 'colsample_bytree': 0.9586652064044978}. Best is trial 22 with value: 5564.337688439678.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002604 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005296 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007823 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:44:05,138] Trial 25 finished with value: 5632.015448559393 and parameters: {'n_estimators': 278, 'num_leaves': 125, 'learning_rate': 0.03724650126220917, 'subsample': 0.779480579742091, 'colsample_bytree': 0.9562535643781083}. Best is trial 22 with value: 5564.337688439678.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003763 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005310 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007861 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:44:19,369] Trial 26 finished with value: 5721.671756329527 and parameters: {'n_estimators': 260, 'num_leaves': 128, 'learning_rate': 0.039342907041825095, 'subsample': 0.7757115830535749, 'colsample_bytree': 0.8457124322939966}. Best is trial 22 with value: 5564.337688439678.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002524 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005308 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.015193 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:44:35,248] Trial 27 finished with value: 5823.916169981577 and parameters: {'n_estimators': 332, 'num_leaves': 150, 'learning_rate': 0.07303758773833631, 'subsample': 0.8000722552141524, 'colsample_bytree': 0.898683187007654}. Best is trial 22 with value: 5564.337688439678.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002691 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005310 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008487 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:44:44,402] Trial 28 finished with value: 5972.085909378805 and parameters: {'n_estimators': 209, 'num_leaves': 120, 'learning_rate': 0.1473017674867284, 'subsample': 0.8992787828784653, 'colsample_bytree': 0.9410349223728849}. Best is trial 22 with value: 5564.337688439678.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002560 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2305
[LightGBM] [Info] Number of data points in the train set: 36135, number of used features: 29
[LightGBM] [Info] Start training from score 42635.661438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004843 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 72270, number of used features: 29
[LightGBM] [Info] Start training from score 43730.893433
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007467 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2411
[LightGBM] [Info] Number of data points in the train set: 108405, number of used features: 29
[LightGBM] [Info] Start training from score 42625.395147

[I 2026-04-20 19:44:59,226] Trial 29 finished with value: 5790.476973701329 and parameters: {'n_estimators': 297, 'num_leaves': 140, 'learning_rate': 0.04673656930322416, 'subsample': 0.8243159293638767, 'colsample_bytree': 0.7452972821669402}. Best is trial 22 with value: 5564.337688439678.

Best Params: {'n_estimators': 294, 'num_leaves': 113, 'learning_rate': 0.014560582047605566, 'subsample': 0.8220865020527265, 'colsample_bytree': 0.9632820171720197}
Best Score: 5564.337688439678

In [102]:
formatted_data = []
for wape, mae, mse, rmse, mape, params in mean_metric_scores:
    # Combine metrics and the params dictionary into one flat dict
    row = {
        'WAPE': wape, 'MAE': mae, 'MSE': mse, 
        'RMSE': rmse, 'MAPE': mape
    }
    row.update(params)
    formatted_data.append(row)

df = pd.DataFrame(formatted_data)
df

,WAPE,MAE,MSE,RMSE,MAPE,n_estimators,num_leaves,learning_rate,subsample,colsample_bytree,random_state
0,0.138148,5911.578657,6.457992e+07,8022.879032,0,663,42,0.049571,0.612108,0.612862,42
1,0.134649,5767.128768,6.240716e+07,7881.649490,0,405,126,0.079728,0.614895,0.875110,42
2,0.147219,6292.973879,7.199119e+07,8478.878547,0,646,134,0.175769,0.809866,0.661866,42
3,0.141567,6052.546914,6.697364e+07,8175.737309,0,444,76,0.133480,0.985123,0.928810,42
4,0.154122,6585.433539,7.782999e+07,8813.504686,0,640,94,0.252334,0.759457,0.899931,42
5,0.145921,6239.074919,7.093730e+07,8417.641415,0,643,65,0.178887,0.604339,0.674126,42
6,0.134058,5742.279253,6.161622e+07,7830.990586,0,494,117,0.029544,0.849402,0.862593,42
7,0.144389,6173.889406,6.984324e+07,8347.682031,0,318,135,0.286164,0.930966,0.855048,42
8,0.141101,6031.296557,6.653895e+07,8151.495527,0,765,49,0.070190,0.875471,0.749882,42
9,0.142572,6097.160664,6.806301e+07,8241.538926,0,386,110,0.184340,0.865129,0.760803,42
10,0.133668,5722.638807,6.111277e+07,7802.078826,0,526,101,0.022902,0.731376,0.980455,42
11,0.131842,5649.111948,6.024358e+07,7737.410645,0,534,100,0.011728,0.730895,0.998220,42
12,0.131585,5637.733865,6.013142e+07,7730.646844,0,547,96,0.010592,0.713576,0.986503,42
13,0.137537,5888.200937,6.407308e+07,7991.929299,0,237,82,0.111166,0.694973,0.991201,42
14,0.138321,5926.084412,6.493543e+07,8039.583682,0,550,24,0.087870,0.688685,0.958053,42
15,0.133465,5715.815050,6.116058e+07,7802.733920,0,558,148,0.019516,0.680743,0.824075,42
16,0.154829,6602.903824,7.739050e+07,8789.225915,0,746,95,0.213676,0.773283,0.933831,42
17,0.143929,6152.239920,6.840472e+07,8264.420042,0,467,62,0.116585,0.733719,0.998898,42
18,0.130080,5573.198910,5.977459e+07,7703.781677,0,320,105,0.010724,0.805870,0.925707,42
19,0.133192,5706.306102,6.087147e+07,7780.907050,0,210,76,0.053237,0.812692,0.913842,42
20,0.135961,5818.316611,6.280865e+07,7914.051082,0,329,117,0.054503,0.655796,0.802144,42
21,0.134274,5746.681359,6.162201e+07,7837.680234,0,592,98,0.023828,0.735520,0.951767,42
22,0.129910,5564.337688,5.910141e+07,7665.312729,0,294,113,0.014561,0.822087,0.963282,42
23,0.134050,5741.164750,6.164219e+07,7832.862636,0,286,109,0.050584,0.906946,0.895446,42
24,0.137872,5899.546824,6.466952e+07,8031.881262,0,379,86,0.095126,0.836987,0.958665,42
25,0.131447,5632.015449,5.975374e+07,7707.383363,0,278,125,0.037247,0.779481,0.956254,42
26,0.133590,5721.671756,6.113251e+07,7800.077597,0,260,128,0.039343,0.775712,0.845712,42
27,0.136062,5823.916170,6.306556e+07,7929.385043,0,332,150,0.073038,0.800072,0.898683,42
28,0.139609,5972.085909,6.563494e+07,8093.000556,0,209,120,0.147302,0.899279,0.941035,42
29,0.135148,5790.476974,6.225730e+07,7867.534111,0,297,140,0.046737,0.824316,0.745297,42

In [103]:
df.to_csv('lightgbm_errorfile_sales.csv', header=True, index=False)

In [104]:
study.best_params

{'n_estimators': 294,
 'num_leaves': 113,
 'learning_rate': 0.014560582047605566,
 'subsample': 0.8220865020527265,
 'colsample_bytree': 0.9632820171720197}